**Question :** Perform element wise mathematical operations such as sign, ceil, round for array3 = array([[-2, 3.5, -4], [4.05, -6, 8]]).

**Level:** Medium

**Input format :**

array

**Output format :**

array

**Sample input :**

Array is [[-2, 3.5, -4], [4.05, -6, 8]]

**Sample output :**

    [[-1.  1. -1.]
     
     [ 1. -1.  1.]]

    [[-2.  4. -4.]
     
     [ 5. -6.  8.]]

    [[-2.  4. -4.]
     
     [ 4. -6.  8.]]

In [1]:
import numpy as np

array3 = np.array([[-2, 3.5, -4], [4.05, -6, 8]])
print(np.sign(array3))
print(np.ceil(array3))
print(np.round(array3))

[[-1.  1. -1.]
 [ 1. -1.  1.]]
[[-2.  4. -4.]
 [ 5. -6.  8.]]
[[-2.  4. -4.]
 [ 4. -6.  8.]]
