**Question**: Perform single dimensional slicing on 1d array [ 6, 7, 8, 9, 0, 1, 2, 3, 4, 5]


**Description :**  Perform single dimensional slicing on 1d array [ 6, 7, 8, 9, 0, 1, 2, 3, 4, 5] where, slice 

From index 4 to last index 

From index 0 to 4 index

From index 4(included) up to index 7(excluded)

Exclude last element

**Level:** Medium

**Input format :**

array

**Output format :**

integer

**Sample input :**

[ 6, 7, 8, 9, 0, 1, 2, 3, 4, 5]

**Sample output :**

[0 1 2 3 4 5]

[6 7 8 9]

[0 1 2]

[6 7 8 9 0 1 2 3 4]

In [1]:
import numpy as np

array1d = np.array([ 6, 7, 8, 9, 0, 1, 2, 3, 4, 5]) 
print(array1d[4:])  
print(array1d[:4])  
print(array1d[4:7])  
print(array1d[:-1]) 

[0 1 2 3 4 5]
[6 7 8 9]
[0 1 2]
[6 7 8 9 0 1 2 3 4]
