**Question :**

Perform flipping the order of axes on numpy array [[1, 2, 3], [4, 5, 6], [7, 8, 9]] where Permute the dimensions of an array, Flip array in the left/right direction and also up/down direction and Rotate an array by 90 degrees in the plane specified by axes.

**Level :** Hard

**Input format :**

array

**Output format :**

array

**Sample input :**

Array is [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

**Sample output  :**

[[1 4 7]
 [2 5 8]
 [3 6 9]]

[[3 2 1]
 [6 5 4]
 [9 8 7]]

[[7 8 9]
 [4 5 6]
 [1 2 3]]

[[3 6 9]
 [2 5 8]
 [1 4 7]]

In [1]:
import numpy as np
array2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arrayT = np.transpose(array2d)
print(arrayT)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [2]:
arrayFlr = np.fliplr(array2d)
print(arrayFlr)

[[3 2 1]
 [6 5 4]
 [9 8 7]]


In [3]:
arrayFud = np.flipud(array2d)
print(arrayFud)

[[7 8 9]
 [4 5 6]
 [1 2 3]]


In [4]:
arrayRot90 = np.rot90(array2d)
print(arrayRot90)

[[3 6 9]
 [2 5 8]
 [1 4 7]]
