**Question :**

Create an array of values with ‘a’ as 1,2,3 and ‘b’ as 4,5,6. Concatenate both arrays.

**Level :** Easy

**Input format :**

input as integer values

input as two arrays

**Output format :**

output as numpy arrays

**Sample input :**

Create both arrays in different variables and concatenate them

First is [1,2,3]

Second is [4, 5, 6]


**Sample output :**

[1, 2, 3]

[4, 5, 6]

[1, 2, 3, 4, 5, 6]

In [1]:
import numpy as np

a = np.array([1, 2, 3])
print(a)

[1 2 3]


In [2]:
b = np.array([4, 5, 6])
print(b)

[4 5 6]


In [3]:
np.concatenate([a,b])

array([1, 2, 3, 4, 5, 6])