**Question :**

Create a numpy array which contains values from 1(inclusive) to 9(inclusive) and save it in 'a'. Return the elements from 4 to end. Reverse the array 'a'.

**Level :** Easy

**Input format :**

input as a range

input as an array

input as integer

**Output format :**

array as output

array as output

array as output

**Sample input :**

Using numpy arange() define the values start from 0 and stop 20 and step as 2

Prints the values ranges from 3 to 9

Use slicing operator to reverse the range of values from 9 to 1


**Sample output :** 

array ([0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20)]

array ([3,4,5,6,7,8,9])

array ([9,8,7,6,5,4,3,2,1])

In [1]:
import numpy as np
a=np.arange(1, 10, 1)
print(a)

[1 2 3 4 5 6 7 8 9]


In [2]:
x = np.arange(10)
print(x[4:])

[4 5 6 7 8 9]


In [3]:
a=x[::-1]
print(a)

[9 8 7 6 5 4 3 2 1 0]
