**Question** :

Create numpy array’s where first array has only ones, second has zeros and third has 1-d array


**Description :**

Create a numpy array with 10 ones and data type as integer

Create a numpy array with 5 rows and 5 columns filled with zeros and data type as float

Create a numpy array with following values[9, 3, 6, 5, 8, 4] and store it in ‘abc’ variable

**Level :** Medium

**Input format :**

input with data type as integer

input with data type as float

input as integers

**Output format :**

Numpy array with ones

numpy array matrix

array of given values

**Sample input :**

Print Ones as length of 5 

Print array of zeros as 3x5 matrix with dtype as float 

Create an array([4, 3, 4, 4, 8, 4])


**Sample output :**

([1,1,1,1,1])

array([[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]])

array([4, 3, 4, 4, 8, 4])

In [1]:
import numpy as np
np.ones(10, dtype='int')

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [2]:
np.zeros((5,5), dtype=float)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [3]:
abc=np.array([9,3,6,5,8,4])
print(abc)

[9 3 6 5 8 4]
