**Question**: For a given list apply relu activation function with alpha, max_value and threshold values.

**Description :** Below is the given list and dtype 

tf.constant([-10, -5, 0.0, 5, 10], dtype = tf.float32)

* Apply the relu activation function on the list using tf.keras

* Apply the relu activation function on the list using tf.keras with alpha = 0.5

* Apply the relu activation function on the list using tf.keras with max_value = 5

* Apply the relu activation function on the list using tf.keras with threshold = 5

Use the same list by using different above activation values and see the difference


**Level :** Medium

**Input format :**  

Data in list format

**Output format :** 

array

**Sample Input :** 

alpha=0.5

**Sample Output :**

array([-5. , -2.5,  0. ,  5. , 10. ], dtype=float32)

In [1]:

import tensorflow as tf
foo = tf.constant([-10, -5, 0.0, 5, 10], dtype = tf.float32)
tf.keras.activations.relu(foo).numpy()



array([ 0.,  0.,  0.,  5., 10.], dtype=float32)

In [2]:
tf.keras.activations.relu(foo, alpha=0.5).numpy()

array([-5. , -2.5,  0. ,  5. , 10. ], dtype=float32)

In [3]:
tf.keras.activations.relu(foo, max_value=5).numpy()

array([0., 0., 0., 5., 5.], dtype=float32)

In [4]:
tf.keras.activations.relu(foo, threshold=5).numpy()

array([-0., -0.,  0.,  0., 10.], dtype=float32)