**Question** : Load mnist dataset using inbuilt function and split into training and testing. Normalize mnist test images. Print normalized test images.

**Level** : Easy


**input format** :
    
Dataset


**output format** :
    
array


**Sample input** :
    
Load the dataset using inbuilt function


**Sample output** : <br/>
[[[-0.5 -0.5 -0.5 ... -0.5 -0.5 -0.5] <br/>
  [-0.5 -0.5 -0.5 ... -0.5 -0.5 -0.5] <br/>
  [-0.5 -0.5 -0.5 ... -0.5 -0.5 -0.5] <br/>
  ...
  [-0.5 -0.5 -0.5 ... -0.5 -0.5 -0.5]  <br/>
  [-0.5 -0.5 -0.5 ... -0.5 -0.5 -0.5]  <br/>
  [-0.5 -0.5 -0.5 ... -0.5 -0.5 -0.5]]  <br/>


In [1]:
import tensorflow as tf

In [2]:
(train_images, train_labels), (test_images, test_labels) = tf.keras.datasets.mnist.load_data()

train_images1 = (train_images / 255) - 0.5
print(train_images1)
test_images1 = (test_images / 255) - 0.5
print(test_images1)

[[[-0.5 -0.5 -0.5 ... -0.5 -0.5 -0.5]
  [-0.5 -0.5 -0.5 ... -0.5 -0.5 -0.5]
  [-0.5 -0.5 -0.5 ... -0.5 -0.5 -0.5]
  ...
  [-0.5 -0.5 -0.5 ... -0.5 -0.5 -0.5]
  [-0.5 -0.5 -0.5 ... -0.5 -0.5 -0.5]
  [-0.5 -0.5 -0.5 ... -0.5 -0.5 -0.5]]

 [[-0.5 -0.5 -0.5 ... -0.5 -0.5 -0.5]
  [-0.5 -0.5 -0.5 ... -0.5 -0.5 -0.5]
  [-0.5 -0.5 -0.5 ... -0.5 -0.5 -0.5]
  ...
  [-0.5 -0.5 -0.5 ... -0.5 -0.5 -0.5]
  [-0.5 -0.5 -0.5 ... -0.5 -0.5 -0.5]
  [-0.5 -0.5 -0.5 ... -0.5 -0.5 -0.5]]

 [[-0.5 -0.5 -0.5 ... -0.5 -0.5 -0.5]
  [-0.5 -0.5 -0.5 ... -0.5 -0.5 -0.5]
  [-0.5 -0.5 -0.5 ... -0.5 -0.5 -0.5]
  ...
  [-0.5 -0.5 -0.5 ... -0.5 -0.5 -0.5]
  [-0.5 -0.5 -0.5 ... -0.5 -0.5 -0.5]
  [-0.5 -0.5 -0.5 ... -0.5 -0.5 -0.5]]

 ...

 [[-0.5 -0.5 -0.5 ... -0.5 -0.5 -0.5]
  [-0.5 -0.5 -0.5 ... -0.5 -0.5 -0.5]
  [-0.5 -0.5 -0.5 ... -0.5 -0.5 -0.5]
  ...
  [-0.5 -0.5 -0.5 ... -0.5 -0.5 -0.5]
  [-0.5 -0.5 -0.5 ... -0.5 -0.5 -0.5]
  [-0.5 -0.5 -0.5 ... -0.5 -0.5 -0.5]]

 [[-0.5 -0.5 -0.5 ... -0.5 -0.5 -0.5]
  [-0.5 -0.5