**Question** : Load mnist dataset using inbuilt function and split into training and testing sets.. Flatten mnist test images. Print flattened test images. 

**Level** : Easy


**input format** :
    
Dataset


**output format** :
    
array


**Sample input** :
    
Load the dataset using inbuilt function


**Sample output** :
    
      [[0, 0, 0, ..., 0, 0, 0], 
       [0, 0, 0, ..., 0, 0, 0], 
       [0, 0, 0, ..., 0, 0, 0], 
       ..., 
       [0, 0, 0, ..., 0, 0, 0], 
       [0, 0, 0, ..., 0, 0, 0], 
       [0, 0, 0, ..., 0, 0, 0]], 


In [2]:
import tensorflow as tf

In [3]:
(train_images, train_labels), (test_images, test_labels) = tf.keras.datasets.mnist.load_data()
train_images = train_images.reshape((-1, 784))
test_images = test_images.reshape((-1, 784))
print(test_images)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
