**Question** : Load mnist dataset using inbuilt function and split into training and testing. Normalize mnist train, test images. Flatten mnist train images. Print flattened train images.

**Level** : Easy



**input format** :
    
Dataset


**output format** :
    
array



**Sample input** :
    
Load the dataset using inbuilt function


**Sample output** :
    
       [[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]],




In [1]:
import tensorflow as tf

In [2]:
(train_images, train_labels), (test_images, test_labels) = tf.keras.datasets.mnist.load_data()
train_images1 = (train_images / 255) - 0.5
test_images1 = (test_images / 255) - 0.5
train_images = train_images.reshape((-1, 784))
print(train_images1)

[[[-0.5 -0.5 -0.5 ... -0.5 -0.5 -0.5]
  [-0.5 -0.5 -0.5 ... -0.5 -0.5 -0.5]
  [-0.5 -0.5 -0.5 ... -0.5 -0.5 -0.5]
  ...
  [-0.5 -0.5 -0.5 ... -0.5 -0.5 -0.5]
  [-0.5 -0.5 -0.5 ... -0.5 -0.5 -0.5]
  [-0.5 -0.5 -0.5 ... -0.5 -0.5 -0.5]]

 [[-0.5 -0.5 -0.5 ... -0.5 -0.5 -0.5]
  [-0.5 -0.5 -0.5 ... -0.5 -0.5 -0.5]
  [-0.5 -0.5 -0.5 ... -0.5 -0.5 -0.5]
  ...
  [-0.5 -0.5 -0.5 ... -0.5 -0.5 -0.5]
  [-0.5 -0.5 -0.5 ... -0.5 -0.5 -0.5]
  [-0.5 -0.5 -0.5 ... -0.5 -0.5 -0.5]]

 [[-0.5 -0.5 -0.5 ... -0.5 -0.5 -0.5]
  [-0.5 -0.5 -0.5 ... -0.5 -0.5 -0.5]
  [-0.5 -0.5 -0.5 ... -0.5 -0.5 -0.5]
  ...
  [-0.5 -0.5 -0.5 ... -0.5 -0.5 -0.5]
  [-0.5 -0.5 -0.5 ... -0.5 -0.5 -0.5]
  [-0.5 -0.5 -0.5 ... -0.5 -0.5 -0.5]]

 ...

 [[-0.5 -0.5 -0.5 ... -0.5 -0.5 -0.5]
  [-0.5 -0.5 -0.5 ... -0.5 -0.5 -0.5]
  [-0.5 -0.5 -0.5 ... -0.5 -0.5 -0.5]
  ...
  [-0.5 -0.5 -0.5 ... -0.5 -0.5 -0.5]
  [-0.5 -0.5 -0.5 ... -0.5 -0.5 -0.5]
  [-0.5 -0.5 -0.5 ... -0.5 -0.5 -0.5]]

 [[-0.5 -0.5 -0.5 ... -0.5 -0.5 -0.5]
  [-0.5 -0.5