**Question** : Load mnist dataset using inbuilt function and split into training and testing sets. Normalize mnist train, test images. Flatten train,test images. Find out the shape of mnist test images.

**Level** : Medium


**input format** :
    
Dataset


**output format** :
    
Dataset dimensions



**Sample input** :
    
Load the dataset using inbuilt function


**Sample output** :
    
(10000, 784)




In [1]:
import tensorflow as tf

In [2]:
(train_images, train_labels), (test_images, test_labels) = tf.keras.datasets.mnist.load_data()
train_images1 = (train_images / 255) - 0.5
test_images1 = (test_images / 255) - 0.5
train_images = train_images.reshape((-1, 784))
test_images = test_images.reshape((-1, 784))
print(test_images1)
print(test_images1.shape)

[[[-0.5 -0.5 -0.5 ... -0.5 -0.5 -0.5]
  [-0.5 -0.5 -0.5 ... -0.5 -0.5 -0.5]
  [-0.5 -0.5 -0.5 ... -0.5 -0.5 -0.5]
  ...
  [-0.5 -0.5 -0.5 ... -0.5 -0.5 -0.5]
  [-0.5 -0.5 -0.5 ... -0.5 -0.5 -0.5]
  [-0.5 -0.5 -0.5 ... -0.5 -0.5 -0.5]]

 [[-0.5 -0.5 -0.5 ... -0.5 -0.5 -0.5]
  [-0.5 -0.5 -0.5 ... -0.5 -0.5 -0.5]
  [-0.5 -0.5 -0.5 ... -0.5 -0.5 -0.5]
  ...
  [-0.5 -0.5 -0.5 ... -0.5 -0.5 -0.5]
  [-0.5 -0.5 -0.5 ... -0.5 -0.5 -0.5]
  [-0.5 -0.5 -0.5 ... -0.5 -0.5 -0.5]]

 [[-0.5 -0.5 -0.5 ... -0.5 -0.5 -0.5]
  [-0.5 -0.5 -0.5 ... -0.5 -0.5 -0.5]
  [-0.5 -0.5 -0.5 ... -0.5 -0.5 -0.5]
  ...
  [-0.5 -0.5 -0.5 ... -0.5 -0.5 -0.5]
  [-0.5 -0.5 -0.5 ... -0.5 -0.5 -0.5]
  [-0.5 -0.5 -0.5 ... -0.5 -0.5 -0.5]]

 ...

 [[-0.5 -0.5 -0.5 ... -0.5 -0.5 -0.5]
  [-0.5 -0.5 -0.5 ... -0.5 -0.5 -0.5]
  [-0.5 -0.5 -0.5 ... -0.5 -0.5 -0.5]
  ...
  [-0.5 -0.5 -0.5 ... -0.5 -0.5 -0.5]
  [-0.5 -0.5 -0.5 ... -0.5 -0.5 -0.5]
  [-0.5 -0.5 -0.5 ... -0.5 -0.5 -0.5]]

 [[-0.5 -0.5 -0.5 ... -0.5 -0.5 -0.5]
  [-0.5 -0.5

In [4]:
print(train_images.shape)

(60000, 784)


In [5]:
print(test_images.shape)

(10000, 784)
