**Question :**

Perform element wise mathematical operations such as add, power, remainder, reciprocal, sign, ceil, round for array1 = array([[10, 20, 30], [40, 50, 60]]),
array2 = array([[2, 3, 4], [4, 6, 8]]), array3 = array([[-2, 3.5, -4], [4.05, -6, 8]]).

**Level :** Hard

**Input format :**

array

**Output format :**

array

**Sample input :**

First array is [[10, 20, 30], [40, 50, 60]]

Second array is [[2, 3, 4], [4, 6, 8]]

Third array is [[-2, 3.5, -4], [4.05, -6, 8]]


**Sample output :**

[[12 23 34]
 [44 56 68]]

[[            100            8000          810000]
 [        2560000     15625000000 167961600000000]]

[[2 3 4]
 [4 1 3]]

[[-0.5         0.28571429 -0.25      ]
 [ 0.24691358 -0.16666667  0.125     ]]

[[-1.  1. -1.]
 [ 1. -1.  1.]]

[[-2.  4. -4.]
 [ 5. -6.  8.]]

[[-2.  4. -4.]
 [ 4. -6.  8.]]

In [ ]:
import numpy as np

# write your code here

