**Question :** Perform flipping the order of axes on a numpy 2d array [[1, 2, 3], [4, 5, 6], [7, 8, 9]] where Flip the array in the up/down direction.

**Level:** Easy

**Input format :**

array

**Output format :**

array

**Sample input :**

Array is [[1, 2, 3], [4, 5, 6], [7, 8, 9]]


**Sample output  :**

    [[7 8 9]
     [4 5 6]
     [1 2 3]]

In [ ]:
import numpy as np

# write your code here
