**Question :** Rotate an array by 90 degrees in the plane specified by axes. [[1, 2, 3], [4, 5, 6], [7, 8, 9]] 

**Level :** Easy

**Input format :**

array

**Output format :**

array

**Sample input :**

Array is [[1, 2, 3], [4, 5, 6], [7, 8, 9]]


**Sample output  :**
    
    [[3 6 9]
    
     [2 5 8]
    
     [1 4 7]]

In [ ]:
import numpy as np

# write your code here
