**Question** :  Perform single dimensional slicing on 1d array [0, 1, 2, 3, 4, 5, 6, 7, 8, 9] 


**Description :**

Perform single dimensional slicing on 1d array [0, 1, 2, 3, 4, 5, 6, 7, 8, 9] where, slice 

From index 4 to last index 

From index 0 to 4 index

From index 4(included) up to index 7(excluded)

Exclude last element

Up to second last index(negative index)

From last to first in reverse order(negative step)

All odd numbers in reversed order

All even numbers in reversed order

All elements

**Level :** Hard

**Input format :**

array

**Output format :**

integer

**Sample input :**

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

**Sample output  :**

[4 5 6 7 8 9]

[0 1 2 3]

[4 5 6]

[0 1 2 3 4 5 6 7 8]

[0 1 2 3 4 5 6 7]

[9 8 7 6 5 4 3 2 1 0]

[9 7 5 3 1]

[8 6 4 2 0]

[0 1 2 3 4 5 6 7 8 9]

In [ ]:
import numpy as np

# write your code here

