**Question :** Perform element wise mathematical operations such as add, power for array1 = array([[40, 50, 60], [70, 80, 90]]), array2 = array([[4, 6, 8], [8, 10, 12]]).

**Level:** Medium

**Input format :**

array

**Output format :** 

array

**Sample input :**

First array is [[40, 50, 60], [70, 80, 90]]

Second array is [[4, 6, 8], [8, 10, 12]]


**Sample output :**

    [[ 44  56  68]

      [ 78  90 102]]

    [[             2560000          15625000000      167961600000000]
 
      [     576480100000000 -7709325833709551616 -8562031566944792576]]

In [ ]:
import numpy as np

# write your code here

