**Question**: Perform single dimensional slicing on 1d array [ 6, 7, 8, 9, 0, 1, 2, 3, 4, 5]

**Description :**  Perform single dimensional slicing on 1d array [ 6, 7, 8, 9, 0, 1, 2, 3, 4, 5] where, slice 

Up to second last index(negative index)

From last to first in reverse order(negative step)

All odd numbers in reversed order

All even numbers in reversed order

All elements

**Level:** Medium

**Input format :**

array

**Output format :**

integer

**Sample input :**

[ 6, 7, 8, 9, 0, 1, 2, 3, 4, 5] 

**Sample output  :**

[6 7 8 9 0 1 2 3]

[5 4 3 2 1 0 9 8 7 6]

[5 3 1 9 7]

[4 2 0 8 6]

[6 7 8 9 0 1 2 3 4 5]

In [ ]:
import numpy as np

# write your code here
