**Question**: Create an array which belongs to gaussian/normal distribution, identity matrix and array with even space.

**Description :**

Create an array containing 5 values with even space between 0 and 1.

Create a 3x3 array which belongs to gaussian/normal distribution with mean 0 and standard deviation.

Create an identity matrix with 3 rows and 3 columns.

**Level :** Easy

**Input format :** 

input as integer

input as integers and matrix 3 x 3

input as integer

**Output format :** 

numpy array with even space

matrix as output

matrix as output

**Sample input :** 

Array with 2 values having even space between 0 and 1.

Create a 2x2 array which belongs to gaussian/normal distribution

identity matrix with 2 rows and 2 columns


**Sample output :** 

array([0., 1.])

array([[ 1.12440535, -0.82887104],
         [ 0.35520822, -0.76821577]])

array([[1.,0.],
       [0.,1.]])

In [ ]:
import numpy as np

# write your code here

