**Question :** Perform flipping the order of axes on a numpy 2d array [[1, 2, 3], [4, 5, 6], [7, 8, 9]] where Flip array in the left/right direction.

**Level:** Easy

**Input format :**

array

**Output format :**

array

**Sample input** :

Array is [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

**Sample output  :**

    [[3 2 1]
     [6 5 4]
     [9 8 7]]

In [ ]:
import numpy as np

# write your code here
